### ISSUE TITLE
Implement a basic todo system

### ISSUE THREAD

**Issue by shanujha** [kagami-org/kagami#1]
This simple system should include

- [x] UI for a todo app
- [x] State management in react
- [ ] State hydration with rust
- [ ] Exchange of data between rust and react

What this first issue should not do: 

- [x] A very complex architecture
- [x] Data models
- [x] Focus on data flow

Focus only on creating a todo view app that shares states with rust backend

**Comment by shanujha** [comment]
Implemented in b2ec0f4e9551278bbead9246c1ed6ce611126fca
